// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvX_z4oCTpJLqjfnBuwg-L6fqihRX9WJw',
    appId: '1:901319599088:web:5f120b7209fd4c3add3335',
    messagingSenderId: '901319599088',
    projectId: 'steasy-aa1ad',
    authDomain: 'steasy-aa1ad.firebaseapp.com',
    storageBucket: 'steasy-aa1ad.firebasestorage.app',
    measurementId: 'G-R781NBFMFW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_q-Ry9IHfIRqWpIc3GnEY8SfbTKBS9Cs',
    appId: '1:901319599088:android:09db03f1790f3446dd3335',
    messagingSenderId: '901319599088',
    projectId: 'steasy-aa1ad',
    storageBucket: 'steasy-aa1ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNXb-vyRCLR3tsIAeXZXytTleV02ToDtg',
    appId: '1:901319599088:ios:45fff7afc9a90df4dd3335',
    messagingSenderId: '901319599088',
    projectId: 'steasy-aa1ad',
    storageBucket: 'steasy-aa1ad.firebasestorage.app',
    iosBundleId: 'com.example.trio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNXb-vyRCLR3tsIAeXZXytTleV02ToDtg',
    appId: '1:901319599088:ios:45fff7afc9a90df4dd3335',
    messagingSenderId: '901319599088',
    projectId: 'steasy-aa1ad',
    storageBucket: 'steasy-aa1ad.firebasestorage.app',
    iosBundleId: 'com.example.trio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvX_z4oCTpJLqjfnBuwg-L6fqihRX9WJw',
    appId: '1:901319599088:web:e0b7fe3f435b7f2add3335',
    messagingSenderId: '901319599088',
    projectId: 'steasy-aa1ad',
    authDomain: 'steasy-aa1ad.firebaseapp.com',
    storageBucket: 'steasy-aa1ad.firebasestorage.app',
    measurementId: 'G-Q6KBQRLCF4',
  );
}
