// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg0qZmQmbxypGC0T4GOlf6uAREoQXkHQk',
    appId: '1:628524860787:web:d5facda05907bf934cb106',
    messagingSenderId: '628524860787',
    projectId: 'skrim-6c8b7',
    authDomain: 'skrim-6c8b7.firebaseapp.com',
    storageBucket: 'skrim-6c8b7.firebasestorage.app',
    measurementId: 'G-9YSWSGQNTF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfhIMOUb3tFu3ADZdtBTDIIjQxrIgTHUU',
    appId: '1:628524860787:android:ddd88db8aa63102c4cb106',
    messagingSenderId: '628524860787',
    projectId: 'skrim-6c8b7',
    storageBucket: 'skrim-6c8b7.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBjDCO58b5jlpQnhbs41nh8CvYByX0fqs',
    appId: '1:628524860787:ios:eafb04add626a1104cb106',
    messagingSenderId: '628524860787',
    projectId: 'skrim-6c8b7',
    storageBucket: 'skrim-6c8b7.firebasestorage.app',
    iosBundleId: 'com.projects.steasy',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBjDCO58b5jlpQnhbs41nh8CvYByX0fqs',
    appId: '1:628524860787:ios:eafb04add626a1104cb106',
    messagingSenderId: '628524860787',
    projectId: 'skrim-6c8b7',
    storageBucket: 'skrim-6c8b7.firebasestorage.app',
    iosBundleId: 'com.example.trio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBg0qZmQmbxypGC0T4GOlf6uAREoQXkHQk',
    appId: '1:628524860787:web:d5facda05907bf934cb106',
    messagingSenderId: '628524860787',
    projectId: 'skrim-6c8b7',
    authDomain: 'skrim-6c8b7.firebaseapp.com',
    storageBucket: 'skrim-6c8b7.firebasestorage.app',
    measurementId: 'G-9YSWSGQNTF',
  );
}
